#!/usr/bin/env bash
# This script Configures an Nginx server so that /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
cd /var/www/html
rm index.*html
echo 'Holberton School is cool' > index.html
cd /etc/nginx/sites-available
sed -i '36a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=F0ddL6VaAVs permanent;' default
