#!/usr/bin/env bash
# This script does a lot here
file="/var/run/holbertonscript.pid"
pgrep bash | tail -1 > $file
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'rm -rf $file & exit' SIGQUIT, SIGTERM
while true
do
	echo "To infinity and beyond"
done
