#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely, and prints "I am invincible!!!" when receiving a SIGTERM signal
function invincible()
{
	echo "I am invincible!!!"
}
trap invincible SIGTERM
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done

