#!/usr/bin/env bash
# This script runs the FizzBuzz test, printing 1 - 100, multiples of 3 print "Fizz", multiples of 5 print "Buzz", and multiples of 15 print "FizzBuzz"
for ((i = 1; i < 101; i++))
	do
	if ((i % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else echo "$i"
	fi
	done
