#!/usr/bin/env bash
# This script loops 10 times, printing "bad luck" on 4th iteration, "good luck" on 8th iteration, and "Holberton School" for all other iterations
i="0"
while ((i < 10))
do
if ((i == 3))
then echo "bad luck"
elif ((i == 7))
then echo "good luck"
else echo "Holberton School"
fi
i=$((i + 1))
done
