#!/usr/bin/env bash
# This script loops from 1 to 20, displaying different strings at 4, 9, and 17
i="1"
while ((i < 21))
do
echo "$i"
case $i in
4)
	echo "bad luck from China";;
9)
	echo "bad luck from Japan";;
17)
	echo "bad luck from Italy";;
esac
i=$((i + 1))
done
