#!/usr/bin/env bash
# This script prints the hours and mintues of the clock
i="0"
while ((i < 13))
	do
	echo "Hour: $i"
	j="1"
	while ((j < 60))
		do
		echo "$j"
		j=$((j + 1))
	done
	i=$((i + 1))
	done
