#!/usr/bin/env bash
# This script does the same fix as the last problem in 7 lines or less
chmod 644 /etc/nginx/nginx.conf
usermod -aG sudo nginx
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
